steps:
  #コンテナイメージをビルドする
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t=gcr.io/$PROJECT_ID/katten-backend-service', '.']
  #コンテナイメージをpushする
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/katten-backend-service"]
  #もろもろの設定
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "alpha"
      - "run"
      - "deploy"
      - "katten-backend-service"
      - "--image=gcr.io/$PROJECT_ID/katten-backend-service"
      - "--region=asia-northeast1"
      - "--platform=managed"
      # - "--allow-unauthenticated"
